// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHUfJypdYHkYqjjCXAXmgCaT35svyu04I',
    appId: '1:35500064335:web:e81fc8c203a7d7bd94b43a',
    messagingSenderId: '35500064335',
    projectId: 'getx-shopping-cart-e50d4',
    authDomain: 'getx-shopping-cart-e50d4.firebaseapp.com',
    storageBucket: 'getx-shopping-cart-e50d4.appspot.com',
    measurementId: 'G-3KGT2QD0C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCMlVZ3_X1lrqF0UVc8PPTcqNbCEdvJY',
    appId: '1:35500064335:android:43ec856ee10d1e7e94b43a',
    messagingSenderId: '35500064335',
    projectId: 'getx-shopping-cart-e50d4',
    storageBucket: 'getx-shopping-cart-e50d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9pQQrmkEvwMN6F5tOBgwVdjB0__yAnoU',
    appId: '1:35500064335:ios:145570e2b073dbec94b43a',
    messagingSenderId: '35500064335',
    projectId: 'getx-shopping-cart-e50d4',
    storageBucket: 'getx-shopping-cart-e50d4.appspot.com',
    iosClientId: '35500064335-npue9bumr8pf3gadsov9l6tkv8uk6554.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxShoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9pQQrmkEvwMN6F5tOBgwVdjB0__yAnoU',
    appId: '1:35500064335:ios:145570e2b073dbec94b43a',
    messagingSenderId: '35500064335',
    projectId: 'getx-shopping-cart-e50d4',
    storageBucket: 'getx-shopping-cart-e50d4.appspot.com',
    iosClientId: '35500064335-npue9bumr8pf3gadsov9l6tkv8uk6554.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxShoppingCart',
  );
}
